#[target."armv7-unknown-linux-musleabihf"]
#image.name = "alpine:edge"
#image.toolchain = ["x86_64-unknown-linux-musl"]
#pre-build = ["apk add pkgconfig openssl-dev libc-dev git"]

#[target."x86_64-unknown-linux-musl"]
#image.name = "ahuszagh/aarch64-cross:aarch64-unknown-linux-musl"
#image.toolchain = ["linux/arm64=aarch64-unknown-linux-musl","x86_64-unknown-linux-musl","x86_64-unknown-linux-musl",
#    "armv7-unknown-linux-musleabi"]
#pre-build = ["cat /etc/apt/sources.list && cat /etc/apt/sources.list.d/ports.list && software-properties-gtk &&
#apt-get update && apt-get --assume-yes install libssl-dev pkgconfig git"]

#[target."aarch64-unknown-linux-musl"]
#image.name = "ahuszagh/aarch64-cross:aarch64-unknown-linux-musl"
#image.toolchain = ["linux/arm64=aarch64-unknown-linux-musl","x86_64-unknown-linux-musl","aarch64-unknown-linux-musl",
#    "armv7-unknown-linux-musleabi"]
#pre-build = ["diff /etc/apt/sources.list cat /etc/apt/sources.list.d/ports.list |grep '<'|sed  's/<+//g' >
#/etc/apt/sources.list1|mv /etc/apt/sources.list1 /etc/apt/sources.list && apt-get update && apt-get --assume-yes
#install libssl-dev pkgconfig git"]
#
#[target."armv7-unknown-linux-musleabi"]
#image.name = "ahuszagh/aarch64-cross:aarch64-unknown-linux-musl"
#image.toolchain = ["linux/arm64=aarch64-unknown-linux-musl","x86_64-unknown-linux-musl","aarch64-unknown-linux-musl",
    #"armv7-unknown-linux-musleabi"]
#pre-build = ["apt-get update && apt-get --assume-yes install libssl-dev pkgconfig git"]

[target."x86_64-unknown-linux-musl"]
image.name = "docker-registry.schwanzer.online/public/muslcross:arm64"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-musl","x86_64-unknown-linux-musl", "armv7-unknown-linux-musleabi"]
env.passthrough = ["RUSTFLAGS","TARGET_CC=x86_64-linux-musl-gcc"]

[target."aarch64-unknown-linux-musl"]
image.name = "docker-registry.schwanzer.online/public/muslcross:arm64"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-musl","x86_64-unknown-linux-musl", "armv7-unknown-linux-musleabi"]
pre-build = ["apt clean && apt install gcc libssl-dev::arm64 musl-tools -y"]
env.passthrough = ["RUSTFLAGS","TARGET_CC=gcc"]

[target."armv7-unknown-linux-musleabihf"]
image.name = "docker-registry.schwanzer.online/public/muslcross:arm64"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-musl","x86_64-unknown-linux-musl", "armv7-unknown-linux-musleabi"]
pre-build = ["apt clean && apt install gcc libssl-dev:armhf musl-tools -y"]
env.passthrough = ["RUSTFLAGS","TARGET_CC=gcc", "CFLAGS=-mno-outline-atomics"]


[target."aarch64-unknown-linux-gnu"]
image.name="docker-registry.schwanzer.online/public/aarch64-unknown-linux-gnu:local"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-gnu","x86_64-unknown-linux-gnu"]
env.passthrough = ["RUSTFLAGS"]
#pre-build = ["dpkg --add-architecture $CROSS_DEB_ARCH&& apt update && apt install libssl-dev:$CROSS_DEB_ARCH git -y"]

[target."armv7-unknown-linux-gnueabihf"]
image.name="docker-registry.schwanzer.online/public/armv7-unknown-linux-gnueabihf:local"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-gnu","x86_64-unknown-linux-gnu"]
env.passthrough = ["RUSTFLAGS"]
#pre-build = ["dpkg --add-architecture $CROSS_DEB_ARCH&& apt update && apt install libssl-dev:$CROSS_DEB_ARCH git -y"]

[target."x86_64-unknown-linux-gnu"]
image.name="docker-registry.schwanzer.online/public/x86_64-unknown-linux-gnu:local"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-gnu","x86_64-unknown-linux-gnu"]
env.passthrough = ["RUSTFLAGS"]
#pre-build = ["dpkg --add-architecture $CROSS_DEB_ARCH&& apt update && apt install libssl-dev:$CROSS_DEB_ARCH -y"]
